flask-gentelella/app/forms/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'forms_blueprint',
    __name__,
    url_prefix='/forms',
    template_folder='templates',
    static_folder='static'
)

flask-gentelella/app/forms/routes.py
from app.forms import blueprint
from flask_login import login_required
from flask import jsonify, render_template, redirect, request, url_for, flash

from app import db, login_manager
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User, Record

from flask_wtf import FlaskForm,CsrfProtect
from wtforms import StringField,IntegerField,SubmitField
from wtforms.validators import Required, DataRequired
import time

WTF_CSRF_ENABLED = False


class HeatForm(FlaskForm):
    ticketNo_A = StringField(label='ticketNo', render_kw={"required":"required", "class":"form-control"})
    heatNo_A = StringField(label='heatNo', render_kw={"required":"required", "class":"form-control"})
    quantity_A = StringField(label='quantity', render_kw={"required":"required", "class":"form-control"})
    productHeight_A = StringField(label='productHeight', render_kw={"required":"required", "class":"form-control"})
    ringHeight_A = StringField(label='ringHeight', render_kw={"required":"required", "class":"form-control"})
    jobNo_A = StringField(label='jobNo', render_kw={"required":"required", "class":"form-control"})


    ticketNo_B = StringField(label='ticketNo', render_kw={ "class":"form-control"})
    heatNo_B = StringField(label='heatNo', render_kw={ "class":"form-control"})
    quantity_B = StringField(label='quantity', render_kw={ "class":"form-control"})
    productHeight_B = StringField(label='productHeight', render_kw={ "class":"form-control"})
    ringHeight_B = StringField(label='ringHeight', render_kw={ "class":"form-control"})
    jobNo_B = StringField(label='jobNo', render_kw={ "class":"form-control"})
    

    submit = SubmitField('提交', render_kw={"class":"btn btn-success"})



@blueprint.route('/form', methods=['POST','GET'])
def form():
    print('-------request.form------')

    # return jsonify('---success---')

    form = HeatForm()

    if form.validate_on_submit():   # 如果form表单以submit进行提交，且用户填写的字段通过validators验证器，那么条件为真（submit提交方式就是“POST”）
        a_obj = Record(             # 使用flask-sqlalchemy定义的一个表结构 
            AorB = 'A',
            ticketNo = form.ticketNo_A.data,
            heatNo = form.heatNo_A.data,
            quantity = form.quantity_A.data,
            productHeight = form.productHeight_A.data,
            ringHeight = form.ringHeight_A.data,
            jobNo = form.jobNo_A.data,
            datetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        )
        db.session.add(a_obj)

        if form.ticketNo_B.data:
            b_obj = Record(             # 使用flask-sqlalchemy定义的一个表结构 
                AorB = 'B',
                ticketNo = form.ticketNo_B.data,
                heatNo = form.heatNo_B.data,
                quantity = form.quantity_B.data,
                productHeight = form.productHeight_B.data,
                ringHeight = form.ringHeight_B.data,
                jobNo = form.jobNo_B.data,
                datetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            )
            db.session.add(b_obj)

        db.session.commit()
        flash('submit successfully!')


        # 文字提示 flash
        return render_template('form.html', form=form) 
               # 跳转到admin页
    # return render_template('form.html',form=form)
    # if request.method == 'POST':
    #     # request.form.get('userpass')
    #     formData = request.form
    #     print(formData)

    #     a_obj = Record(             # 使用flask-sqlalchemy定义的一个表结构 
    #         AorB = 'A',
    #         ticketNo = formData.get('ticketNo'),
    #         heatNo = formData.get('heatNo'),
    #         quantity = formData.get('quantity'),
    #         productHeight = formData.get('productHeight'),
    #         ringHeight = formData.get('ringHeight'),
    #         jobNo = formData.get('jobNo'),
    #         datetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    #     )
    #     db.session.add(a_obj)

    #     if formData.get('ticketNo_B'):
    #         b_obj = Record(             # 使用flask-sqlalchemy定义的一个表结构 
    #             AorB = 'B',
    #             ticketNo = formData.get('ticketNo_B'),
    #             heatNo = formData.get('heatNo_B'),
    #             quantity = formData.get('quantity_B'),
    #             productHeight = formData.get('productHeight_B'),
    #             ringHeight = formData.get('ringHeight_B'),
    #             jobNo = formData.get('jobNo_B'),
    #             datetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    #         )
    #         db.session.add(b_obj)
    #     db.session.commit()
    #     return render_template('form.html')

    return render_template('form.html', form=form)




# @blueprint.route('/form', methods=['POST','GET'])
# def form():
#     print('-------request.form------')
#     # print(request.form)
#     # record = Record(**request.form)
#     # print(record)
#     # db.session.add(record)
#     # db.session.commit()
    
#     # return jsonify('---success---')

#     # form = HeatForm()
#     # if form.validate_on_submit():   # 如果form表单以submit进行提交，且用户填写的字段通过validators验证器，那么条件为真（submit提交方式就是“POST”）
#     #     new_obj = Record(             # 使用flask-sqlalchemy定义的一个表结构 
#     #       AorB = 'B',
#     #         ticketNo = form.ticketNo.data,
#     #         heatNo = form.heatNo.data,
#     #         quantity = form.quantity.data,
#     #         productHeight = form.productHeight.data,
#     #         ringHeight = form.ringHeight.data,
#     #         jobNo = form.jobNo.data,
#     #         datetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
#     #     )
#     #     db.session.add(new_obj)
#     #     db.session.commit()
#     #     # 文字提示 flash
#     #     return 'ok'         # 跳转到admin页
#     # return render_template('form.html',form=form)
#     if request.method == 'POST':
#         # request.form.get('userpass')
#         formData = request.form
#         new_obj = Record(             # 使用flask-sqlalchemy定义的一个表结构 
#             AorB = 'B',
#             ticketNo = formData.get('ticketNo'),
#             heatNo = formData.get('heatNo'),
#             quantity = formData.get('quantity'),
#             productHeight = formData.get('productHeight'),
#             ringHeight = formData.get('ringHeight'),
#             jobNo = formData.get('jobNo'),
#             datetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
#         )
#         db.session.add(new_obj)
#         db.session.commit()

#         return render_template('form.html',form=form)
#     return render_template('form.html',form=form)


@blueprint.route('/<template>')
@login_required
def route_template(template):
    return render_template(template + '.html')

flask-gentelella/app/forms/templates/form.html
{% extends "base_site.html" %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">

        <div>
              {% with messages = get_flashed_messages() %}
                  {% if messages %}
                      {% for category, message in get_flashed_messages(with_categories=True) %}
                      <div class="alert alert-success alert-dismissible">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                          <h4><i class="icon fa fa-check"></i> 操作成功!</h4>
                              <p class="flash">{{ 'Error: ' if category == 'error' else '' }}{{ message }}</p>
                      </div>
                      {% endfor %}
                  {% endif %}
              {% endwith %}
        </div>

      </div>
      <div class="clearfix"></div>

      <div class="row">


        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>表单录入</h2>

              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              
              <div class="clearfix"></div>

            </div>
            <div class="x_content">

              <form class="form-horizontal form-label-left"  id ="form" method='post' action="/forms/form">
              {{ form.csrf_token }}

                <div class="col-md-6 col-xs-12">

                  <div align="center">
                    <h3>A</h3>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工单号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">

                      {{ form.ticketNo_A }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">炉号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.heatNo_A }}
                   

                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">数量</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.quantity_A }}
                    
                      pcs
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">产品高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.productHeight_A }}
                      
                      mm
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">延长环高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.ringHeight_A }}
                      
                    mm
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.jobNo_A }}
                      

                    </div>
                  </div>
                </div>


                <div class="col-md-6 col-xs-12">

                  <div align="center">
                    <h3>B</h3>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工单号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      
                      {{ form.ticketNo_B }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">炉号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.heatNo_B }}


                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">数量</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.quantity_B }}
  
                      pcs
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">产品高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.productHeight_B }}
                      mm
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">延长环高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.ringHeight_B }}
                    mm
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.jobNo_B }}


                    </div>
                  </div>
                </div>

    

              <!-- <div class="ln_solid"></div> -->
              <div class="ln_solid"></div>
                <div class="col-md-12 col-xs-12" align="right">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <button type="button" class="btn btn-primary">取消 </button>
                    <button type="reset" class="btn btn-primary">重设</button>
                    <input type="submit" class="btn btn-success" value="提交">
<!--                     <button type="submit" class="btn btn-success" onclick=ajaxForm()> Submit</button> -->
                  </div>
                </div>

              </form>


            </div>
          </div>
        </div>



      </div>


    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  

  </script>
{% endblock javascripts %}

flask-gentelella/app/forms/templates/form1.html
{% extends "base_site.html" %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>表单录入</h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>

      <div class="row">


        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Form</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <br />
              <form class="form-horizontal form-label-left"  id ="A_form" method='post'>

                <div class="col-md-6 col-xs-12">

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工单号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <input type="text" class="form-control" name='ticketNo' placeholder="ticketNo_A">
                      <!-- {{ form.ticketNo }} -->
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">炉号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.heatNo }} -->
                      <input type="text" class="form-control" name='heatNo' placeholder="heatNo_A">

                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">数量</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.quantity }} -->
                      <input type="text" class="form-control" name='quantity' placeholder="quantity_A">
                      pcs
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">产品高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.productHeight }} -->
                      <input type="text" class="form-control" name='productHeight' placeholder="productHeight_A">
                      mm
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">延长环高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.ringHeight }} -->
                      <input type="text" class="form-control" name='productHeight' placeholder="productHeight_A">
                    mm
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.jobNo }} -->
                      <input type="text" class="form-control" name='jobNo' placeholder="jobNo_A">

                    </div>
                  </div>
                </div>


                <div class="col-md-6 col-xs-12">

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工单号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <input type="text" class="form-control" name='ticketNo_B' placeholder="ticketNo_B">
                      <!-- {{ form.ticketNo }} -->
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">炉号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.heatNo }} -->
                      <input type="text" class="form-control" name='heatNo_B' placeholder="heatNo_B">

                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">数量</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.quantity }} -->
                      <input type="text" class="form-control" name='quantity_B' placeholder="quantity_B">
                      pcs
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">产品高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.productHeight }} -->
                      <input type="text" class="form-control" name='productHeight_B' placeholder="productHeight_B">
                      mm
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">延长环高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.ringHeight }} -->
                      <input type="text" class="form-control" name='ringHeight_B' placeholder="ringHeight_B">
                    mm
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <!-- {{ form.jobNo }} -->
                      <input type="text" class="form-control" name='jobNo_B' placeholder="jobNo_B">

                    </div>
                  </div>
                </div>

              <br />

              <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <button type="button" class="btn btn-primary">Cancel</button>
                    <button type="reset" class="btn btn-primary">Reset</button>

                    <button type="submit" class="btn btn-success" onclick=ajaxForm()> Submit</button>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>



      </div>


    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  <!-- Parsley -->
  <script src="{{ url_for('static', filename='vendors/parsleyjs/dist/parsley.min.js') }}"></script>

  <script type="text/javascript">
    function ajaxForm(){
            varifyinput();
            var form= new FormData(document.getElementById("A_form"));
            $.ajax({
                url:"{{ url_for('forms_blueprint.form') }}",
                type:"post",
                data:form,
                dataType: 'json',
                processData:false,
                contentType:false,
                success:function(data){
                        create_table(data.result);
                },
                error:function(e){
                        alert("没有取得数据");
                }
            })
        }

    $("#demo_form").submit(function(e){
      e.preventDefault();

        $.ajax({
            url:"/forms/form",
            type:'POST',
            data: $(this).serialize(),   // 这个序列化传递很重要
            headers:{
                "X-CSRF-Token": getCookie('csrf_token')
            },
            success:function (resp) {
                // window.location.href = "/admin/page";
                if(resp.error){
                    console.log(resp.errmsg);
                }
            }
        })
    });

  </script>
{% endblock javascripts %}

flask-gentelella/app/forms/templates/form2.html
{% extends "base_site.html" %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">

        <div class="title_left">
          <h3>表单录入</h3>
        </div>

      
        <div>
              {% with messages = get_flashed_messages() %}
                  {% if messages %}
                      {% for category, message in get_flashed_messages(with_categories=True) %}
                      <div class="alert alert-success alert-dismissible">
                          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                          <h4><i class="icon fa fa-check"></i> 操作成功!</h4>
                              <p class="flash">{{ 'Error: ' if category == 'error' else '' }}{{ message }}</p>
                      </div>
                      {% endfor %}
                  {% endif %}
              {% endwith %}
        </div>


        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>

      <div class="row">


        <div class="col-md-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Form</h2>

              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <form class="form-horizontal form-label-left"  id ="form" method='post' action="/forms/form">
              {{ form.csrf_token }}

                <div class="col-md-6 col-xs-12">

                  <div align="center">
                    <h3>A</h3>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工单号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">

                      {{ form.ticketNo_A }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">炉号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.heatNo_A }}
                   

                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">数量</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.quantity_A }}
                    
                      pcs
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">产品高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.productHeight_A }}
                      
                      mm
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">延长环高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.ringHeight_A }}
                      
                    mm
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.jobNo_A }}
                      

                    </div>
                  </div>
                </div>


                <div class="col-md-6 col-xs-12">

                  <div align="center">
                    <h3>B</h3>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工单号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      
                      {{ form.ticketNo_B }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">炉号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.heatNo_B }}


                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">数量</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.quantity_B }}
  
                      pcs
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">产品高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.productHeight_B }}
                      mm
                    </div>
                  </div>


                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">延长环高度</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.ringHeight_B }}
                    mm
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">工号</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      {{ form.jobNo_B }}


                    </div>
                  </div>
                </div>

    

              <!-- <div class="ln_solid"></div> -->
              <div class="ln_solid"></div>
                <div class="col-md-12 col-xs-12" align="right">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <button type="button" class="btn btn-primary">Cancel</button>
                    <button type="reset" class="btn btn-primary">Reset</button>
                    <input type="submit" class="btn btn-success" value="Submit">
<!--                     <button type="submit" class="btn btn-success" onclick=ajaxForm()> Submit</button> -->
                  </div>
                </div>

              </form>


            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ super()}}
  

  </script>
{% endblock javascripts %}